services:
  qcoordinaciondb:
    container_name: qcoordinaciondb
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: qcoordinacion
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: ${SPRING_APPLICATION_POSTGRES_USER}
      # You can use whatever password you like
      POSTGRES_PASSWORD: ${SPRING_APPLICATION_POSTGRES_PASSWORD}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '5433:5432'
    expose:
      # Opens port 3306 on the container
      - '5433'
      # Where our data will be persisted
    volumes:
      - qcoordinaciondb:/var/lib/postgresql/data

  keycloak:
    image: bitnami/keycloak:22.0.1
    container_name: keycloak-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: ${SPRING_APPLICATION_KC_POSTGRES_HOST}
      KEYCLOAK_DATABASE_PORT: ${SPRING_APPLICATION_KC_POSTGRES_PORT}
      KEYCLOAK_DATABASE_NAME: ${SPRING_APPLICATION_KC_POSTGRES_DB}
      KEYCLOAK_DATABASE_USER: ${SPRING_APPLICATION_KC_POSTGRES_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${SPRING_APPLICATION_KC_POSTGRES_PASSWORD}
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_HTTP_PORT: 8181
      KC_HTTP_PORT: 8181

    ports:
      - 8181:8181
    expose:
      - 8181

# Names our volume
volumes:
  qcoordinaciondb: