services:
  qcoordinacion-database:
    container_name: qc-database
    image: mysql:8.0.3
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: 'QCoordinacionDatabase'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${SPRING_APPLICATION_MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${SPRING_APPLICATION_MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${SPRING_APPLICATION_MYSQL_ROOT_PASSWORD}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - qcoordinacion-database:/var/lib/mysql

  ###Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - qcoordinacion-database
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: db_keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: user
      DB_PASSWORD : 1234
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181


# Names our volume
volumes:
  qcoordinacion-database: