services:
  qcoordinaciondb:
    container_name: qcoordinaciondb
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: qcoordinacion
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: ${SPRING_APPLICATION_POSTGRES_USER}
      # You can use whatever password you like
      POSTGRES_PASSWORD: ${SPRING_APPLICATION_POSTGRES_PASSWORD}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '5433:5432'
    expose:
      # Opens port 3306 on the container
      - '5433'
      # Where our data will be persisted
    volumes:
      - qcoordinaciondb:/var/lib/postgresql/data

  ###Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - qcoordinacion-database
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: db_keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: user
      DB_PASSWORD : 1234
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181


# Names our volume
volumes:
  qcoordinaciondb: