version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # Exponer RabbitMQ al host
      - "15672:15672"  # Exponer la interfaz de gestión al host


  keycloak:
    image: bitnami/keycloak:22.0.1
    container_name: keycloak-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: ${SPRING_APPLICATION_KC_POSTGRES_HOST}
      KEYCLOAK_DATABASE_PORT: ${SPRING_APPLICATION_KC_POSTGRES_PORT}
      KEYCLOAK_DATABASE_NAME: ${SPRING_APPLICATION_KC_POSTGRES_DB}
      KEYCLOAK_DATABASE_USER: ${SPRING_APPLICATION_KC_POSTGRES_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${SPRING_APPLICATION_KC_POSTGRES_PASSWORD}
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_HTTP_PORT: 8181
      KC_HTTP_PORT: 8181

    ports:
      - 8181:8181
    expose:
      - 8181
