spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchanges:
    requests: fhir-requests-exchange
  queues:
    requests: fhir-requests-queue
  routing-keys:
    requests: fhir.requests.routing-key
