eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000,http://otro-origen-permitido.com"
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "*"
            allowCredentials: true
